<a href="https://colab.research.google.com/github/Sashimimeow/-SC_Data_Visualization/blob/main/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd
import os

In [50]:

from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
#เข้าไป path ใน google drive
import os
os.chdir('/content/drive/Shareddrives')

!pwd #เช็ค path ที่กำลังทำงานอยู่

/content/drive/Shareddrives

In [52]:
import pandas as pd
import os
os.chdir('/content/drive/MyDrive/Data-Viz-2023-2')

In [53]:
!ls

ectreport2023.xlsx			 POS_transactions_20171207-20171219.csv
ectreport66.xlsx			 POS_transactions_20190213-20190226.csv
Final.pdf				 POS_transactions_20190328-20190410.csv
POS_operator_logs_20171207-20171219.csv  table_merge_result.csv
POS_operator_logs_20190213-20190226.csv  thai.json
POS_operator_logs_20190328-20190410.csv

In [61]:
operator1 = pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_operator_logs_20171207-20171219.csv')
operator2 = pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_operator_logs_20190213-20190226.csv')
operator3  = pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_operator_logs_20190328-20190410.csv')
tran1 = pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_transactions_20171207-20171219.csv')
tran2 = pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_transactions_20190213-20190226.csv')
tran3= pd.read_csv('/content/drive/MyDrive/Data-Viz-2023-2/POS_transactions_20190328-20190410.csv')

In [62]:
operator1 = operator1 .head()
operator2 = operator1 .head()
operator3 = operator1 .head()

In [63]:
operator1 .info()
operator2 .info()
operator3 .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  5 non-null      int64
 1   WorkstationID       5 non-null      int64
 2   TranID              5 non-null      int64
 3   BeginDateTime       5 non-null      object
 4   OperatorID          5 non-null      int64
 5   Items               5 non-null      object
dtypes: int64(4), object(2)
memory usage: 368.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  5 non-null      int64
 1   WorkstationID       5 non-null      int64
 2   TranID              5 non-null      int64
 3   BeginDateTime       5 non-null      object
 4   OperatorID          5 non-null      int64
 5   Items               5 non-null      object
dtypes: int64(4), object(2)
memory usage: 368.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  5 non-null      int64
 1   WorkstationID       5 non-null      int64
 2   TranID              5 non-null      int64
 3   BeginDateTime       5 non-null      object
 4   OperatorID          5 non-null      int64
 5   Items               5 non-null      object
dtypes: int64(4), object(2)
memory usage: 368.0+ bytes

In [64]:
operator1 .describe()

       WorkstationGroupID  WorkstationID        TranID  OperatorID
count                 5.0       5.000000  5.000000e+00    5.000000
mean                  8.0      16.000000  1.712071e+12  266.000000
std                   0.0       1.581139  1.581139e+01    1.581139
min                   8.0      14.000000  1.712071e+12  264.000000
25%                   8.0      15.000000  1.712071e+12  265.000000
50%                   8.0      16.000000  1.712071e+12  266.000000
75%                   8.0      17.000000  1.712071e+12  267.000000
max                   8.0      18.000000  1.712071e+12  268.000000

In [65]:
operator2 .describe()

       WorkstationGroupID  WorkstationID        TranID  OperatorID
count                 5.0       5.000000  5.000000e+00    5.000000
mean                  8.0      16.000000  1.712071e+12  266.000000
std                   0.0       1.581139  1.581139e+01    1.581139
min                   8.0      14.000000  1.712071e+12  264.000000
25%                   8.0      15.000000  1.712071e+12  265.000000
50%                   8.0      16.000000  1.712071e+12  266.000000
75%                   8.0      17.000000  1.712071e+12  267.000000
max                   8.0      18.000000  1.712071e+12  268.000000

In [66]:
operator2 .describe()

       WorkstationGroupID  WorkstationID        TranID  OperatorID
count                 5.0       5.000000  5.000000e+00    5.000000
mean                  8.0      16.000000  1.712071e+12  266.000000
std                   0.0       1.581139  1.581139e+01    1.581139
min                   8.0      14.000000  1.712071e+12  264.000000
25%                   8.0      15.000000  1.712071e+12  265.000000
50%                   8.0      16.000000  1.712071e+12  266.000000
75%                   8.0      17.000000  1.712071e+12  267.000000
max                   8.0      18.000000  1.712071e+12  268.000000

In [67]:
tran1.info()
tran2.info()
tran3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66863 entries, 0 to 66862
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  66863 non-null  int64
 1   TranID              66863 non-null  int64
 2   BeginDateTime       66863 non-null  object
 3   EndDateTime         66863 non-null  object
 4   OperatorID          66863 non-null  int64
 5   TranTime            66863 non-null  int64
 6   BreakTime           66863 non-null  int64
 7   ArtNum              66863 non-null  int64
 8   TNcash              66863 non-null  bool
 9   TNcard              66863 non-null  bool
 10  Amount              66863 non-null  float64
dtypes: bool(2), float64(1), int64(6), object(2)
memory usage: 4.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47066 entries, 0 to 47065
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  47066 non-null  int64
 1   TranID              47066 non-null  int64
 2   BeginDateTime       47066 non-null  object
 3   EndDateTime         47066 non-null  object
 4   OperatorID          47066 non-null  int64
 5   TranTime            47066 non-null  int64
 6   BreakTime           47066 non-null  int64
 7   ArtNum              47066 non-null  int64
 8   TNcash              47066 non-null  bool
 9   TNcard              47066 non-null  bool
 10  Amount              47066 non-null  float64
dtypes: bool(2), float64(1), int64(6), object(2)
memory usage: 3.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49340 entries, 0 to 49339
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  49340 non-null  int64
 1   TranID              49340 non-null  float64
 2   BeginDateTime       49340 non-null  object
 3   EndDateTime         49340 non-null  object
 4   OperatorID          49340 non-null  int64
 5   TranTime            49340 non-null  int64
 6   BreakTime           49340 non-null  int64
 7   ArtNum              49340 non-null  int64
 8   TNcash              49340 non-null  bool
 9   TNcard              49340 non-null  bool
 10  Amount              49340 non-null  float64
dtypes: bool(2), float64(2), int64(5), object(2)
memory usage: 3.5+ MB

#Check NULL

In [80]:
operator1.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [81]:
operator2.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [82]:
operator3.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [83]:
tran1.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [84]:
tran2.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [85]:
tran3.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [86]:
operator = pd.concat([operator1,operator2,operator3],ignore_index=True)

In [89]:
transactions = pd.concat([tran1,tran2,tran3],ignore_index = True)

In [90]:
operator

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
5,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
6,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
7,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
8,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
9,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
10,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
11,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
12,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
13,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
14,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn

In [45]:
aaa = transactions.merge(operator,how='left' , left_on='OperatorID' , right_on = 'OperatorID')
aaa

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,NaN,NaN,NaN,NaN,NaN
1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,NaN,NaN,NaN,NaN,NaN
2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,NaN,NaN,NaN,NaN,NaN
3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,NaN,NaN,NaN,NaN,NaN
4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,NaN,NaN,NaN,NaN,NaN
5,1,1.902231e+13,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,NaN,NaN,NaN,NaN,NaN
6,1,1.902131e+11,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19,NaN,NaN,NaN,NaN,NaN
7,1,1.902131e+11,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20,NaN,NaN,NaN,NaN,NaN
8,1,1.902131e+11,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20,NaN,NaN,NaN,NaN,NaN
9,1,1.902131e+11,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20,NaN,NaN,NaN,NaN,NaN
10,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,NaN,NaN,NaN,NaN,NaN
11,1,1.903291e+13,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,NaN,NaN,NaN,NaN,NaN
12,1,1.903291e+13,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,NaN,NaN,NaN,NaN,NaN
13,1,1.903291e+13,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,NaN,NaN,NaN,NaN,NaN
14,1,1.903291e+13,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,NaN,NaN,NaN,NaN,NaN

In [47]:
transactions

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
5,1,1.902231e+13,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79
6,1,1.902131e+11,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19
7,1,1.902131e+11,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20
8,1,1.902131e+11,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20
9,1,1.902131e+11,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20
10,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99
11,1,1.903291e+13,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74
12,1,1.903291e+13,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47
13,1,1.903291e+13,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18
14,1,1.903291e+13,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70

In [48]:
operator

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
5,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
6,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
7,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
8,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
9,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
10,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
11,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
12,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
13,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
14,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn

In [46]:
data = pd.merge(transactions,operator=on'data')

SyntaxError: ignored